services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodbcontainer
    ports:
      - "27017:27017"   # Exposing MongoDB on localhost:27017
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart:
      - always

  # Node.js Backend Service
  backend:
    build:
      context: ./backend  # Path to the backend directory with Dockerfile
    container_name: backendcontainer
    ports:
      - "3000:3000"       # Exposing backend on localhost:3000
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/foodsdb?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network
    restart:
      - always

  # HTML/JavaScript Frontend Service
  frontend:
    build:
      context: ./frontend  # Path to the frontend directory with Dockerfile
    container_name: frontendcontainer
    ports:
      - "8080:80"       # Exposing frontend on localhost:8080
    depends_on:
      - backend
    networks:
      - app-network
    restart:
      - always

# Named Volumes
volumes:
  mongo_data:

# Network
networks:
  app-network:
    driver: bridge