name: Docker Image CI

on:
  [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the backend Docker image
      #run: docker build -t dimilan/3sdevops-backend:latest ./backend
      run: |
        docker build -t dimilan/3sdevops-backend:latest ./backend 
        docker build -t dimilan/3sdevops-frontend:latest ./frontend